name: Reviewer lottery
on:
  pull_request:
    types: [opened]

jobs:
  test:
    if: {{ github.actor == 'dependabot' || github.actor == 'sashaobucina' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: uesteibar/reviewer-lottery@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
